---
- name: Einrichten des DCs f체r die Ausfalldom채ne des Schulungsbereichs
  hosts: schulungdc
  gather_facts: false
  tasks:

    - name: Firewall disablen um sp채tere Probleme zu vermeiden
      win_firewall:
        state: disabled
        profiles:
          - Domain
          - Private
          - Public

    - name: Anpassung des Hostnamens
      win_hostname:
        name: "schulung-dc"
      register: temp1

    - name: Neustart vor DC Installation
      win_reboot:
        pre_reboot_delay: 5
        post_reboot_delay: 10

    - name: DC Rolle installieren und konfigurieren
      win_feature:
        name: AD-Domain-Services
        include_management_tools: yes
        include_sub_features: yes
        state: present

    - name: Setze Loopback als DNS Server
      win_dns_client:
        adapter_names: '*'
        dns_servers:
          - 127.0.0.1
          - <INSERT_YOUR_OWN_INFO_HERE>

    - name: Erstellen der Dom채ne
      microsoft.ad.domain:
        create_dns_delegation: false
        database_path: C:\Windows\NTDS
        dns_domain_name: ausfall-S.internal
        domain_mode: Win2012R2
        forest_mode: Win2012R2
        safe_mode_password: P@ssw0rd
        sysvol_path: C:\Windows\SYSVOL
      register: creation_domain

    - name: Neustart nach DC Promo
      win_reboot:
        pre_reboot_delay: 15
        post_reboot_delay: 15
      when: creation_domain.reboot_required

    - name: Setze Reverse DNS Lookup Zone
      win_shell: "Add-DnsServerPrimaryZone -NetworkID '<INSERT_YOUR_OWN_INFO_HERE>' -ReplicationScope Forest"
      retries: 5
      delay: 60
      register: temp4
      until: temp4 is succeeded

    - name: Installiere DHCP-Server
      win_feature:
        name: DHCP
        include_management_tools: yes

    - name: DHCP Sicherheitsgruppen anlegen
      win_command:
        cmd: netsh dhcp add securitygroups

    - name: DHCP Service neustarten
      win_service:
        name: dhcpserver
        state: restarted

    - name: Authorisieren des DHCP Servers
      ansible.windows.win_powershell:
        script: |
           Add-DHCPServerInDC -DnsName schulung-dc.ausfall-S.internal -IPAddress <INSERT_YOUR_OWN_INFO_HERE>

    - name: Servermanager informieren das DHCP richtig konfiguriert wurde
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\ServerManager\Roles\12
        name: ConfigurationState
        data: 2
        type: dword
        state: present

    - name: Neustart
      win_reboot:
        pre_reboot_delay: 5
