---
- name: Konfigurieren der Domäne durch Hochladen und Ausführen eines PS Skripts
  hosts: schulungdc
  gather_facts: no
  tasks:

    - name: Hochladen create_user_schulung.ps1 zu Schulung-DC
      win_copy:
        src: /opt/scripts/templates/create_user_schulung.ps1
        dest: C:\Temp\

    - name: Hochladen gpoimport.ps1 zu Schulung-DC
      win_copy:
        src: /opt/scripts/templates/gpoimport_schulung.ps1
        dest: C:\Temp\

    - name: Hochladen Ordner gpobackup zu Schulung-DC
      win_copy:
        src: /opt/scripts/templates/gpobackupS
        dest: C:\Temp\

    - name: Hochladen dhcpexport.xml zu Schulung-DC
      win_copy:
        src: /opt/scripts/templates/dhcpexport_schulung.xml
        dest: C:\Temp\

    - name: Hochladen reimport_dhcp.ps1 zu Schulung-DC
      win_copy:
        src: /opt/scripts/templates/reimport_dhcp_schulung.ps1
        dest: C:\Temp\

    - name: Hochladen relinkgpo.ps1 zu Schulung-DC
      win_copy:
        src: /opt/scripts/templates/relinkgpo_schulung.ps1
        dest: C:\Temp\

    - name: Ausführen des Skripts zum Reimport der DHCP Einstellungen
      win_command: powershell.exe -ExecutionPolicy Bypass -File "C:/Temp/reimport_dhcp_schulung.ps1"
      become: yes
      become_user: Administrator@ausfall-S.internal
      become_method: runas

    - name: Ausführen des Skripts zur Erstellung der Accounts & OUs
      win_command: powershell.exe -ExecutionPolicy Bypass -File "C:\Temp\create_user_schulung.ps1"
      become: yes
      become_user: Administrator@ausfall-S.internal
      become_method: runas

    - name: Ausführen des Skripts zum Import der GPOs
      win_command: powershell.exe -ExecutionPolicy Bypass -File "C:\Temp\gpoimport_schulung.ps1"
      become: yes
      become_user: Administrator@ausfall-S.internal
      become_method: runas

    - name: Ausführen des Skripts zum Verlinken der GPOs
      win_command: powershell.exe -ExecutionPolicy Bypass -File "C:\Temp\relinkgpo_schulung.ps1"
      become: yes
      become_user: Administrator@ausfall-S.internal
      become_method: runas
