---
- name: Konfigurieren der Domäne durch Hochladen und Ausführen eines PS Skripts
  hosts: verwaltungdc
  gather_facts: no
  tasks:

    - name: Hochladen create_user_verwaltung.ps1 zu Verwaltung-DC
      win_copy:
        src: /opt/scripts/templates/create_user_verwaltung.ps1
        dest: C:\Temp\

    - name: Hochladen gpoimport_verwaltung.ps1 zu Verwaltung-DC
      win_copy:
        src: /opt/scripts/templates/gpoimport_verwaltung.ps1
        dest: C:\Temp\

    - name: Hochladen Ordner gpobackupV zu Verwaltung-DC
      win_copy:
        src: /opt/scripts/templates/gpobackupV
        dest: C:\Temp\

    - name: Hochladen dhcpexport_verwaltung.xml zu Verwaltung-DC
      win_copy:
        src: /opt/scripts/templates/dhcpexport_verwaltung.xml
        dest: C:\Temp\

    - name: Hochladen reimport_dhcp_verwaltung.ps1 zu Verwaltung-DC
      win_copy:
        src: /opt/scripts/templates/reimport_dhcp_verwaltung.ps1
        dest: C:\Temp\

    - name: Hochladen relinkgpo_verwaltung.ps1 zu Verwaltung-DC
      win_copy:
        src: /opt/scripts/templates/relinkgpo_verwaltung.ps1
        dest: C:\Temp\

    - name: Ausführen des Skripts zum Reimport der DHCP Einstellungen
      win_command: powershell.exe -ExecutionPolicy Bypass -File "C:/Temp/reimport_dhcp_verwaltung.ps1"
      become: yes
      become_user: Administrator@ausfall-V.internal
      become_method: runas

    - name: Ausführen des Skripts zur Erstellung der Accounts & OUs
      win_command: powershell.exe -ExecutionPolicy Bypass -File "C:/Temp/create_user_verwaltung.ps1"
      become: yes
      become_user: Administrator@ausfall-V.internal
      become_method: runas

    - name: Ausführen des Skripts zum Import der GPOs
      win_command: powershell.exe -ExecutionPolicy Bypass -File "C:/Temp/gpoimport_verwaltung.ps1"
      become: yes
      become_user: Administrator@ausfall-V.internal
      become_method: runas

    - name: Ausführen des Skripts zum Verlinken der GPOs
      win_command: powershell.exe -ExecutionPolicy Bypass -File "C:/Temp/relinkgpo_verwaltung.ps1"
      become: yes
      become_user: Administrator@ausfall-V.internal
      become_method: runas
